apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: vibetribe-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repo-url
      default: https://github.com/VibeTribeOrganization/VibeTribe.git
    - name: git-revision
      default: main

  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: vibetribe-ci-run-       
        namespace: tekton-pipelines
        annotations:
          tekton.dev/no-affinity-assistant: "true"
          pipeline.tekton.dev/disable-affinity-assistant: "true"
      spec:
        pipelineRef:
          name: vibetribe-ci-pipeline
        taskRunTemplate:
          serviceAccountName: pipeline
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: source-volume
          - name: env-config
            configMap:
              name: frontend-env-config
        params:
          - name: git-repo-url
            value: $(params.git-repo-url)      
          - name: git-revision
            value: $(params.git-revision)      
          - name: backend-image
            value: harbor.local/vibetribe/backend:latest
          - name: frontend-image
            value: harbor.local/vibetribe/frontend:latest
